version: '3'

services:
  ros2_cuda_pytorch:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ros2_cuda_pytorch
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    tty: true
    command: bash -c ". /opt/ros/foxy/setup.sh && . install/setup.sh && nvidia-smi && bash"
    volumes:
      - ../../../..:/workspace/ros2_ws/src
      - ~/mt-matthew:/workspace/viewpoint_planning
      - ~/viewpoint-learning:/workspace/viewpoint_learning
      - ~/Hierarchical-Localization:/workspace/Hierarchical-Localization